export const patientDownloadsCopy = {
  title: "Summary reports",
  description:
    "AI-prepared plain English summaries of your health records. Download and keep a copy for your personal records.",
  table: {
    columns: ["Document", "Type", "Summary date", "Download"],
    downloadTxtLabel: "TXT",
    downloadPdfLabel: "PDF",
    downloadGroupAria: (fileName: string) =>
      `Download options for ${fileName}`,
    downloadTxtAria: (fileName: string) =>
      `Download plain-language TXT report for ${fileName}`,
    downloadPdfAria: (fileName: string) =>
      `Download plain-language PDF report for ${fileName}`,
    documentTypeFallback: "Health record",
  },
  empty: {
    title: "No summary reports yet",
    description:
      "After you upload health records, AI prepares plain English summaries. They will appear here when ready to download.",
    processing: (count: number) =>
      `${count} ${count === 1 ? "summary is" : "summaries are"} still being prepared.`,
    regenerateLabel: "Retry summary",
    cta: "Upload health records",
  },
  notice:
    "These summaries are generated by AI for your information — not medical advice.",
} as const;
